"""added approver id field to the stool test record

Revision ID: 17875ab78e78
Revises: f40b3c618498
Create Date: 2023-09-21 01:33:54.123016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17875ab78e78'
down_revision = 'f40b3c618498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approver_id')

    # ### end Alembic commands ###
