"""added updater ID

Revision ID: 1862a0ba3b80
Revises: 80bcffc45976
Create Date: 2023-03-26 11:14:11.347697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1862a0ba3b80'
down_revision = '80bcffc45976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updater_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updater_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updater_id')

    # ### end Alembic commands ###
