"""added stool exam and stool report item model

Revision ID: 19d3b248d05c
Revises: d83b3612f858
Create Date: 2023-03-10 12:54:49.389661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d3b248d05c'
down_revision = 'd83b3612f858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stool_test_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_number')
    )
    op.create_table('stool_test_report_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['stool_test_records.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stool_test_report_items')
    op.drop_table('stool_test_records')
    op.drop_table('stages')
    op.drop_table('organisms')
    # ### end Alembic commands ###
