"""added suggestion field

Revision ID: 2a67bc9ec1ba
Revises: e6733f99864e
Create Date: 2023-03-22 16:06:39.411408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a67bc9ec1ba'
down_revision = 'e6733f99864e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('suggestion')

    # ### end Alembic commands ###
