"""added collection datetime

Revision ID: 3b705eda8f80
Revises: 6a36c4ecbf24
Create Date: 2023-03-25 12:56:26.893983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b705eda8f80'
down_revision = '6a36c4ecbf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.drop_column('collection_datetime')

    # ### end Alembic commands ###
