"""added updater ID field

Revision ID: 5ac219a6c47b
Revises: 424ba3b95ab5
Create Date: 2023-03-26 12:02:23.274350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac219a6c47b'
down_revision = '424ba3b95ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_physical_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updater_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updater_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_physical_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updater_id')

    # ### end Alembic commands ###
