"""added report datetime field

Revision ID: 6eb849c8079a
Revises: 19d3b248d05c
Create Date: 2023-03-10 13:08:38.025578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb849c8079a'
down_revision = '19d3b248d05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.drop_column('reported_at')

    # ### end Alembic commands ###
