"""added reporter and updater ID to the record field

Revision ID: 80bcffc45976
Revises: 02800049a8c7
Create Date: 2023-03-26 11:00:16.616746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bcffc45976'
down_revision = '02800049a8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updater_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updater_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reporter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updater_id')
        batch_op.drop_column('reporter_id')

    # ### end Alembic commands ###
