"""moved is quantitative field to Test model

Revision ID: 8a4e7e2febd5
Revises: 2bce9c1b4725
Create Date: 2024-03-24 12:16:38.479720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4e7e2febd5'
down_revision = '2bce9c1b4725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_column('is_quantitative')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quantitative', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('is_quantitative')

    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quantitative', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
