"""added min and max fields

Revision ID: ab58b988c581
Revises: 1f75a3360d67
Create Date: 2023-03-13 17:54:30.539872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab58b988c581'
down_revision = '1f75a3360d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_value', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('max_value', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('max_value')
        batch_op.drop_column('min_value')

    # ### end Alembic commands ###
