"""replaced fasting datetime field with fasting time

Revision ID: debd2012845d
Revises: 5ac219a6c47b
Create Date: 2023-03-29 20:17:33.108856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'debd2012845d'
down_revision = '5ac219a6c47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fasting_time', sa.Numeric(), nullable=True))
        batch_op.drop_column('fasting_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fasting_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fasting_time')

    # ### end Alembic commands ###
