"""added test profile model and assoc table

Revision ID: e2d89607dda5
Revises: 8a4e7e2febd5
Create Date: 2024-06-24 00:07:38.311735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d89607dda5'
down_revision = '8a4e7e2febd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_test_profiles',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['test_profile_id'], ['test_profiles.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'test_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_test_profiles')
    op.drop_table('test_profiles')
    # ### end Alembic commands ###
