"""added method and quality field to the stool record model

Revision ID: f40b3c618498
Revises: af6552610af0
Create Date: 2023-09-21 00:53:48.693904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40b3c618498'
down_revision = 'af6552610af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stool_test_records', schema=None) as batch_op:
        batch_op.drop_column('quality')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
