"""added note field

Revision ID: f4eacacb481b
Revises: 3442e5bab5d7
Create Date: 2023-03-10 10:48:04.345030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4eacacb481b'
down_revision = '3442e5bab5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
